import {
    mobile,
    backend,
    creator,
    web,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    redux,
    tailwind,
    nodejs,
    mongodb,
    git,
    figma,
    docker,
    threejs,
  } from "../assets";
  
export const navLinks = [
    {
      id: "about",
      title: "About",
    },
    {
      id: "work",
      title: "Experience",
    },
    { 
      id: "projects",
      title: "Projects",  
    },
    {
      id: "contact",
      title: "Contact",
    },
    { 
      id: "resume",
      title: "Resume",  
    },
   
];
  
const services = [
    {
      title: "Web Developer",
      icon: web,
    },
    {
      title: "React Native Developer",
      icon: mobile,
    },
    {
      title: "Backend Developer",
      icon: backend,
    },
    {
      title: "Content Creator",
      icon: creator,
    },
];
  
const technologies = [
    {
      name: "HTML 5",
      icon: html,
    },
    {
      name: "CSS 3",
      icon: css,
    },
    {
      name: "JavaScript",
      icon: javascript,
    },
    {
      name: "TypeScript",
      icon: typescript,
    },
    {
      name: "React JS",
      icon: reactjs,
    },
    {
      name: "Redux Toolkit",
      icon: redux,
    },
    {
      name: "Tailwind CSS",
      icon: tailwind,
    },
    {
      name: "Node JS",
      icon: nodejs,
    },
    {
      name: "MongoDB",
      icon: mongodb,
    },
    {
      name: "Three JS",
      icon: threejs,
    },
    {
      name: "git",
      icon: git,
    },
    {
      name: "figma",
      icon: figma,
    },
    {
      name: "docker",
      icon: docker,
    },
];

const techColors = {
  React: "text-blue-400",
  "Node.js": "text-green-400",
  Express: "text-gray-400",
  MongoDB: "text-emerald-400",
  AWS: "text-yellow-400",
  PostgreSQL: "text-teal-400",
  TailwindCSS: "text-sky-400",
  Python: "text-indigo-400",
  TypeScript: "text-blue-500",
  JavaScript: "text-yellow-500",
  C: "text-blue-600",
  "C++": "text-blue-500",
  Java: "text-red-500",
  JavaFX: "text-orange-400",
  Kotlin: "text-purple-500",
  Swift: "text-orange-500",
  Go: "text-cyan-400",
  Rust: "text-orange-600",
  Dart: "text-sky-500",
  PHP: "text-indigo-500",
  Ruby: "text-red-400",
  "C#": "text-violet-500",
  HTML: "text-orange-500",
  CSS: "text-blue-400",
  SASS: "text-pink-400",
  SCSS: "text-pink-500",
  GraphQL: "text-pink-500",
  Firebase: "text-yellow-500",
  MySQL: "text-blue-400",
  SQLite: "text-gray-500",
  Redis: "text-red-500",
  Docker: "text-blue-500",
  Kubernetes: "text-blue-600",
  Jenkins: "text-red-500",
  Git: "text-orange-500",
  GitHub: "text-gray-600",
  GitLab: "text-orange-600",
  Bash: "text-gray-600",
  Linux: "text-gray-400",
  R: "text-blue-500",
  MATLAB: "text-yellow-600",
  Terraform: "text-purple-400",
  Ansible: "text-red-400",
  Cloudflare: "text-orange-400",
  NextJS: "text-gray-600",
  Vue: "text-green-400",
  Angular: "text-red-500",
  Svelte: "text-orange-500",
  Astro: "text-yellow-500",
  Deno: "text-gray-400",
  WebAssembly: "text-purple-500",
  OpenGL: "text-green-500",
  Unreal: "text-blue-700",
  Unity: "text-gray-500",
  Blender: "text-orange-600",
  TensorFlow: "text-orange-400",
  PyTorch: "text-red-400",
  NumPy: "text-blue-400",
  Pandas: "text-teal-400",
  ScikitLearn: "text-yellow-500",
  FastAPI: "text-green-500",
  Flask: "text-gray-400",
  Django: "text-green-500",
  Spring: "text-green-600",
  ASPNET: "text-blue-500",
  Bootstrap: "text-purple-500",
  ChakraUI: "text-teal-400",
  Tailwind: "text-sky-400",
  Bulma: "text-green-400",
  "Electron.js": "text-gray-400",
  ThreeJS: "text-yellow-400",
  WebGL: "text-teal-500",
  "RxJS": "text-red-500",
  Jest: "text-pink-500",
  Mocha: "text-brown-500",
  Cypress: "text-green-500",
  Playwright: "text-purple-500",
  RabbitMQ: "text-orange-500",
  Kafka: "text-red-500",
  "OpenAPI": "text-teal-500",
  Prometheus: "text-orange-500",
  Grafana: "text-yellow-500",
  ELK: "text-gray-500",
  Loki: "text-green-500",
  Default: "text-purple-400",
};

const techColorsBubbles = {
  React: "bg-blue-600",
  "Node.js": "bg-green-600",
  Express: "bg-gray-600",
  MongoDB: "bg-emerald-600",
  AWS: "bg-yellow-600",
  PostgreSQL: "bg-teal-600",
  TailwindCSS: "bg-sky-600",
  Python: "bg-indigo-600",
  TypeScript: "bg-blue-600",
  JavaScript: "bg-yellow-600",
  C: "bg-blue-600",
  "C++": "bg-blue-600",
  Java: "bg-red-600",
  JavaFX: "bg-orange-600",
  Kotlin: "bg-purple-600",
  Swift: "bg-orange-600",
  Go: "bg-cyan-600",
  Rust: "bg-orange-600",
  Dart: "bg-sky-600",
  PHP: "bg-indigo-600",
  Ruby: "bg-red-600",
  "C#": "bg-violet-600",
  HTML: "bg-orange-600",
  CSS: "bg-blue-600",
  SASS: "bg-pink-600",
  SCSS: "bg-pink-600",
  GraphQL: "bg-pink-600",
  Firebase: "bg-yellow-600",
  MySQL: "bg-blue-600",
  SQLite: "bg-gray-600",
  Redis: "bg-red-600",
  Docker: "bg-blue-600",
  Kubernetes: "bg-blue-600",
  Jenkins: "bg-red-600",
  Git: "bg-orange-600",
  GitHub: "bg-gray-600",
  GitLab: "bg-orange-600",
  Bash: "bg-gray-600",
  Linux: "bg-gray-600",
  R: "bg-blue-600",
  MATLAB: "bg-yellow-600",
  Terraform: "bg-purple-600",
  Ansible: "bg-red-600",
  Cloudflare: "bg-orange-600",
  NextJS: "bg-gray-600",
  Vue: "bg-green-600",
  Angular: "bg-red-600",
  Svelte: "bg-orange-600",
  Astro: "bg-yellow-600",
  Deno: "bg-gray-600",
  WebAssembly: "bg-purple-600",
  OpenGL: "bg-green-600",
  Unreal: "bg-blue-700",
  Unity: "bg-gray-600",
  Blender: "bg-orange-600",
  TensorFlow: "bg-orange-600",
  PyTorch: "bg-red-600",
  NumPy: "bg-blue-600",
  Pandas: "bg-teal-600",
  ScikitLearn: "bg-yellow-600",
  FastAPI: "bg-green-600",
  Flask: "bg-gray-600",
  Django: "bg-green-600",
  Spring: "bg-green-600",
  ASPNET: "bg-blue-600",
  Bootstrap: "bg-purple-600",
  ChakraUI: "bg-teal-600",
  Tailwind: "bg-sky-600",
  Bulma: "bg-green-600",
  "Electron.js": "bg-gray-600",
  ThreeJS: "bg-yellow-600",
  WebGL: "bg-teal-600",
  "RxJS": "bg-red-600",
  Jest: "bg-pink-600",
  Mocha: "bg-brown-600",
  Cypress: "bg-green-600",
  Playwright: "bg-purple-600",
  RabbitMQ: "bg-orange-600",
  Kafka: "bg-red-600",
  "OpenAPI": "bg-teal-600",
  Prometheus: "bg-orange-600",
  Grafana: "bg-yellow-600",
  ELK: "bg-gray-600",
  Loki: "bg-green-600",
  Default: "bg-purple-600",
};

  


  
  
  
  export { services, technologies, techColors, techColorsBubbles };